"""add user avatar

Revision ID: 349abc9314c4
Revises: 166b7e877443
Create Date: 2018-01-06 11:42:55.860180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349abc9314c4'
down_revision = '166b7e877443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
