"""Add 'confirmed' column in 'users'

Revision ID: 8bfcf9452a6d
Revises: 890f130a45ab
Create Date: 2017-12-07 17:33:46.445318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfcf9452a6d'
down_revision = '890f130a45ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
